//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlutoDbFirst
{
    using System;
    
    [Flags]
    public enum CourseLevel : short
    {
        BIGGENER = 1,
        INTERMEDIATE = 2,
        EXPERT = 3
    }
}
